# Site Settings
title: Modern Developer
email: your@email.com
description: >- 
  A clean, modern Jekyll theme for web developers
baseurl: ""
url: "https://yourusername.github.io"
twitter_username: yourhandle
github_username: yourhandle

# Build Settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme Settings
sass:
  style: compressed

# Custom variables
color_primary: "#3498db"
color_dark: "#2c3e50"
color_light: "#ecf0f1"
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

